// NOTE item categories: number = 1 :chair, 2 :CHild toys , 3: Wooden Light , 4: Kitchen Accessories

import mockSmallItem from "../Icon/mockSmallItem.svg";
import bg from "../Icon/bg.svg";
import categoriesPic from "../Icon/categories.svg";
import showcase from "../Icon/Showcase.svg";

export const categories = [
  { cover: categoriesPic, name: "Chair", itemCount: 530 },
  { cover: categoriesPic, name: "Child Toys", itemCount: 65 },
  { cover: categoriesPic, name: "Wooden Light", itemCount: 56 },
  { cover: categoriesPic, name: "Kitchen Accessories", itemCount: 20 },
];

export const mockData = {
  heroBg: [
    {
      id: 1,
      picture: bg,
      discount: 30,
      name: "Sofa",
      type: "Stand Table Lighting",
    },
    {
      id: 1,
      picture: bg,
      discount: 30,
      name: "Sofa",
      type: "Stand Table Lighting",
    },
    {
      id: 1,
      picture: bg,
      discount: 30,
      name: "Sofa",
      type: "Stand Table Lighting",
    },
  ],
  itemSmall: [mockSmallItem, mockSmallItem, mockSmallItem],
  showCaseItem: [
    {
      id: 1,
      discount: 30,
      name: "Sofa",
      type: "Stand Table",
      price: 150,
      picture: showcase,
    },
    {
      id: 2,
      discount: 30,
      name: "kook",
      type: "Kitchen Set",
      price: 200,
      picture: showcase,
    },
  ],
  item: [
    {
      id: 1,
      rate: 4,
      comment: 32,
      price: 32,
      categories: 1,
      picture: [],
      discount: 0,
      name: "State Wooden Chair",
      bestSellers: true,
      topProduct: true,
    },
    {
      id: 2,
      rate: 4,
      comment: 32,
      price: 32,
      categories: 1,
      picture: [],
      discount: 0,
      name: "State Wooden Chair",
      bestSellers: true,
      topProduct: true,
    },
    {
      id: 3,
      rate: 4,
      comment: 32,
      price: 32,
      categories: 1,
      picture: [],
      discount: 0,
      name: "State Wooden Chair",
      bestSellers: true,
      topProduct: true,
    },
    {
      id: 4,
      rate: 4,
      comment: 32,
      price: 32,
      categories: 1,
      picture: [],
      discount: 0,
      name: "State Wooden Chair",
      bestSellers: true,
      topProduct: true,
    },
    {
      id: 5,
      rate: 4,
      comment: 32,
      price: 32,
      categories: 2,
      picture: [],
      discount: 0,
      name: "State Wooden Chair",
      bestSellers: true,
      topProduct: true,
    },
    {
      id: 6,
      rate: 4,
      comment: 32,
      price: 32,
      categories: 2,
      picture: [],
      discount: 0,
      name: "State Wooden Chair",
      bestSellers: true,
      topProduct: true,
    },

    {
      id: 7,
      rate: 4,
      comment: 32,
      price: 32,
      categories: 2,
      picture: [],
      discount: 0,
      name: "State Wooden Chair",
      bestSellers: true,
      topProduct: true,
    },

    {
      id: 8,
      rate: 4,
      comment: 32,
      price: 32,
      categories: 2,
      picture: [],
      discount: 0,
      name: "State Wooden Chair",
      bestSellers: true,
      topProduct: true,
    },
    {
      id: 9,
      rate: 4,
      comment: 32,
      price: 32,
      categories: 3,
      picture: [],
      discount: 0,
      name: "State Wooden Chair",
      bestSellers: true,
      topProduct: true,
    },
    {
      id: 10,
      rate: 4,
      comment: 32,
      price: 32,
      categories: 3,
      picture: [],
      discount: 0,
      name: "State Wooden Chair",
      bestSellers: true,
      topProduct: true,
    },
    {
      id: 11,
      rate: 4,
      comment: 32,
      price: 32,
      categories: 3,
      picture: [],
      discount: 0,
      name: "State Wooden Chair",
      bestSellers: true,
      topProduct: true,
    },
    {
      id: 12,
      rate: 4,
      comment: 32,
      price: 32,
      categories: 3,
      picture: [],
      discount: 0,
      name: "State Wooden Chair",
      bestSellers: true,
      topProduct: true,
    },
    {
      id: 13,
      rate: 4,
      comment: 32,
      price: 32,
      categories: 3,
      picture: [],
      discount: 0,
      name: "State Wooden Chair",
      bestSellers: true,
      topProduct: true,
    },
    {
      id: 14,
      rate: 4,
      comment: 32,
      price: 32,
      categories: 4,
      picture: [],
      discount: 0,
      name: "State Wooden Chair",
      bestSellers: true,
      topProduct: true,
    },
    {
      id: 15,
      rate: 4,
      comment: 32,
      price: 32,
      categories: 4,
      picture: [],
      discount: 0,
      name: "State Wooden Chair",
      bestSellers: true,
      topProduct: true,
    },
    {
      id: 16,
      rate: 4,
      comment: 32,
      price: 32,
      categories: 4,
      picture: [],
      discount: 0,
      name: "State Wooden Chair",
      bestSellers: true,
      topProduct: true,
    },
    {
      id: 17,
      rate: 4,
      comment: 32,
      price: 32,
      categories: 4,
      picture: [],
      discount: 0,
      name: "State Wooden Chair",
      bestSellers: true,
      topProduct: true,
    },
    {
      id: 18,
      rate: 4,
      comment: 32,
      price: 32,
      categories: 4,
      picture: [],
      discount: 0,
      name: "State Wooden Chair",
      bestSellers: true,
      topProduct: true,
    },
  ],
  news: [],
};
