// NOTE item categories: number = 1 :chair, 2 :CHild toys , 3: Wooden Light , 4: Kitchen Accessories
// NOTE item  Daily Deal : number = 1 :best sellers, 2 :featured , 3: top products

import mockSmallItem from "../Icon/mockSmallItem.svg";
import bg from "../Icon/bg.svg";
import categoriesPic from "../Icon/categories.svg";
import showcase from "../Icon/Showcase.svg";
import item from "../Icon/item.svg";

import newsCover from "../Icon/mockNewsCover.svg";

export const categories = [
  { cover: categoriesPic, name: "Chair", itemCount: 530 },
  { cover: categoriesPic, name: "Child Toys", itemCount: 65 },
  { cover: categoriesPic, name: "Wooden Light", itemCount: 56 },
  { cover: categoriesPic, name: "Kitchen Accessories", itemCount: 20 },
];

export const mockData = {
  heroBg: [
    {
      id: 1,
      picture: bg,
      discount: 30,
      name: "Sofa",
      type: "Stand Table Lighting",
    },
    {
      id: 1,
      picture: bg,
      discount: 30,
      name: "Sofa",
      type: "Stand Table Lighting",
    },
    {
      id: 1,
      picture: bg,
      discount: 30,
      name: "Sofa",
      type: "Stand Table Lighting",
    },
  ],
  itemSmall: [mockSmallItem, mockSmallItem, mockSmallItem],
  showCaseItem: [
    {
      id: 1,
      discount: 30,
      name: "Sofa",
      type: "Stand Table",
      price: 150,
      picture: showcase,
    },
    {
      id: 2,
      discount: 30,
      name: "kook",
      type: "Kitchen Set",
      price: 200,
      picture: showcase,
    },
  ],
  item: [
    {
      id: 1,
      rate: 4,
      comment: 32,
      price: 32,
      categories: 1,
      picture: [item],
      discount: 30,
      name: "State Wooden Chair",
      dailyDeal: [2],
    },
    {
      id: 2,
      rate: 4,
      comment: 32,
      price: 32,
      categories: 1,
      picture: [item, item, item, item],
      discount: 50,
      name: "State Wooden Chair",

      dailyDeal: [2],
    },
    {
      id: 3,
      rate: 4,
      comment: 32,
      price: 32,
      categories: 1,
      picture: [item, item],
      discount: 50,
      name: "State Wooden Chair",
      dailyDeal: [2],
    },
    {
      id: 4,
      rate: 4,
      comment: 32,
      price: 32,
      categories: 1,
      picture: [item],
      discount: 30,
      name: "State Wooden Chair",
      dailyDeal: [2],
    },
    {
      id: 5,
      rate: 4,
      comment: 32,
      price: 32,
      categories: 2,
      picture: [item],
      discount: 90,
      name: "State Wooden Chair",
      dailyDeal: [2],
    },
    {
      id: 6,
      rate: 4,
      comment: 32,
      price: 32,
      categories: 2,
      picture: [item],
      discount: 60,
      name: "State Wooden Chair",
      dailyDeal: [1],
    },

    {
      id: 7,
      rate: 4,
      comment: 32,
      price: 32,
      categories: 2,
      picture: [item],
      discount: 20,
      name: "State Wooden Chair",
      dailyDeal: [1],
    },

    {
      id: 8,
      rate: 4,
      comment: 32,
      price: 32,
      categories: 2,
      picture: [item],
      discount: 10,
      name: "State Wooden Chair",
      dailyDeal: [1],
    },
    {
      id: 9,
      rate: 4,
      comment: 32,
      price: 32,
      categories: 3,
      picture: [item],
      discount: 50,
      name: "State Wooden Chair",

      dailyDeal: [2],
    },
    {
      id: 10,
      rate: 4,
      comment: 32,
      price: 32,
      categories: 3,
      picture: [item],
      discount: 70,
      name: "State Wooden Chair",

      dailyDeal: [1, 2],
    },
    {
      id: 11,
      rate: 4,
      comment: 32,
      price: 32,
      categories: 3,
      picture: [item],
      discount: 40,
      name: "State Wooden Chair",
      dailyDeal: [1, 2],
    },
    {
      id: 12,
      rate: 4,
      comment: 32,
      price: 32,
      categories: 3,
      picture: [item],
      discount: 30,
      name: "State Wooden Chair",
      dailyDeal: [2],
    },
    {
      id: 13,
      rate: 4,
      comment: 32,
      price: 32,
      categories: 3,
      picture: [item],
      discount: 20,
      name: "State Wooden Chair",
      dailyDeal: [3],
    },
    {
      id: 14,
      rate: 4,
      comment: 32,
      price: 32,
      categories: 4,
      picture: [item],
      discount: 10,
      name: "State Wooden Chair",
      dailyDeal: [1, 2],
    },
    {
      id: 15,
      rate: 4,
      comment: 32,
      price: 32,
      categories: 4,
      picture: [item],
      discount: 10,
      name: "State Wooden Chair",
      dailyDeal: [1, 2],
    },
    {
      id: 16,
      rate: 4,
      comment: 32,
      price: 32,
      categories: 4,
      picture: [item],
      discount: 50,
      name: "State Wooden Chair",
      dailyDeal: [1],
    },
    {
      id: 17,
      rate: 4,
      comment: 32,
      price: 32,
      categories: 4,
      picture: [item],
      discount: 70,
      name: "State Wooden Chair",

      dailyDeal: [1, 2],
    },
    {
      id: 18,
      rate: 4,
      comment: 32,
      price: 32,
      categories: 4,
      picture: [item],
      discount: 80,
      name: "State Wooden Chair",
      dailyDeal: [1, 3],
    },
  ],
  news: [
    {
      id: 1,
      cover: newsCover,
      title: "Saepe Ducimus Veniam Vem",
      content: "Quibusdam sapiente neque irure quas diam, ligula at saepe nunc",
      date: "09 May 21",
      commentCount: 40,
      writer: "RT Shuvro",
    },
    {
      id: 2,
      cover: newsCover,
      title: "Saepe Ducimus Veniam Vem",
      content: "Quibusdam sapiente neque irure quas diam, ligula at saepe nunc",
      date: "04 May 21",
      commentCount: 11,
      writer: "RT Shuvro",
    },
    {
      id: 3,
      cover: newsCover,
      title: "Saepe Ducimus Veniam ",
      content: "Quibusdam sapiente neque irure quas diam",
      date: "05 May 21",
      commentCount: 423,
      writer: "RT Shuvro",
    },
  ],
};
